# This file was generated by GoReleaser. DO NOT EDIT.
class Elasdx < Formula
  desc "An ElasticSearch index template updating, reindexing and cleanup tool"
  homepage "https://github.com/LGUG2Z/elasdx"
  version "0.0.1"

  if OS.mac?
    url "https://github.com/LGUG2Z/elasdx/releases/download/v0.0.1/elasdx_0.0.1_darwin_amd64.tar.gz"
    sha256 "60455c20198fa7ea2b42b0b2ad1b5f17c6d27627fd0e5ce5d9710658353743af"
  elsif OS.linux?
    url "https://github.com/LGUG2Z/elasdx/releases/download/v0.0.1/elasdx_0.0.1_linux_amd64.tar.gz"
    sha256 "d7f0a695ad0ff3b93cb91f9f96e2f800157f1c775654bbd8880f68b366b8f7d4"
  end

  def install
    bin.install "elasdx"
  end

  test do
    system "#{bin}/elasdx --version"
  end
end
