# This file was generated by GoReleaser. DO NOT EDIT.
class Kmval < Formula
  desc "A Kustomize manifest validator"
  homepage "https://github.com/LGUG2Z/kmval"
  version "0.0.1"

  if OS.mac?
    url "https://github.com/LGUG2Z/kmval/releases/download/v0.0.1/kmval_0.0.1_darwin_amd64.tar.gz"
    sha256 "d6b64cf441b0931865595b2a88deeb8c51992b4ee10936910c88d30c9eae6b3b"
  elsif OS.linux?
    url "https://github.com/LGUG2Z/kmval/releases/download/v0.0.1/kmval_0.0.1_linux_amd64.tar.gz"
    sha256 "504114f75f56bb69f11fe8d67561c7a23ad7a6d2f9de571b58fb7617233ba677"
  end
  
  depends_on "yq"
  depends_on "kustomize"

  def install
    bin.install "kmval"
  end

  test do
    system "#{bin}/kmval --version"
  end
end
