# This file was generated by GoReleaser. DO NOT EDIT.
class Rae < Formula
  desc "A docker-compose development environment orchestrator"
  homepage "https://github.com/LGUG2Z/rae"
  url "https://github.com/LGUG2Z/rae/releases/download/v0.0.7/rae_0.0.7_darwin_amd64.tar.gz"
  version "0.0.7"
  sha256 "46c9be33806aa26c3780241f917413795a6e7dd22efda3deddcd35f0dd0c4e44"
  
  depends_on "docker"

  def install
    bin.install "rae"
    bash_completion.install "bash_autocomplete"
    zsh_completion.install "zsh_autocomplete"
  end

  test do
    system "#{bin}/rae --version"
  end
end
