# This file was generated by GoReleaser. DO NOT EDIT.
class Story < Formula
  desc "A workflow tool for implementing stories across a node meta-repo"
  homepage "https://github.com/LGUG2Z/story"
  url "https://github.com/LGUG2Z/story/releases/download/v0.4.0/story_0.4.0_darwin_amd64.tar.gz"
  version "0.4.0"
  sha256 "dd12e82555329d2e47f968493b1735d4ef9989b2720c03674e10f14b31dd6f37"

  def install
    bin.install "story"
    bash_completion.install "bash_autocomplete" => "story"
    zsh_completion.install "zsh_autocomplete" => "_story"
  end

  test do
    system "#{bin}/story --version"
  end
end
