# This file was generated by GoReleaser. DO NOT EDIT.
class Story < Formula
  desc "A workflow tool for implementing stories across a node meta-repo"
  homepage "https://github.com/LGUG2Z/story"
  url "https://github.com/LGUG2Z/story/releases/download/v0.0.1/rae_0.0.1_darwin_amd64.tar.gz"
  version "0.0.1"
  sha256 "7dcb403c18c88e37d814f4cb578fe4fe3c71f5869af5c6b2a4955de2ad1f5ba3"
  
  depends_on "docker"

  def install
    bin.install "story"
    bash_completion.install "bash_autocomplete"
    zsh_completion.install "zsh_autocomplete"
  end

  test do
    system "#{bin}/story --version"
  end
end
