# This file was generated by GoReleaser. DO NOT EDIT.
class Story < Formula
  desc "A workflow tool for implementing stories across a node meta-repo"
  homepage "https://github.com/LGUG2Z/story"
  url "https://github.com/LGUG2Z/story/releases/download/v0.3.8/story_0.3.8_darwin_amd64.tar.gz"
  version "0.3.8"
  sha256 "6deeaf4923a91b6290e58272210ea31baba09e3cbd0dfdd4b3f53f82d3a75874"

  def install
    bin.install "story"
    bash_completion.install "bash_autocomplete" => "story"
    zsh_completion.install "zsh_autocomplete" => "_story"
  end

  test do
    system "#{bin}/story --version"
  end
end
